// Display-name map for the bairros as they appear in the source CSV
// (uppercase, truncated to 15 chars). Key = raw value, value = proper name.

export const BAIRRO_DISPLAY: Record<string, string> = {
  "": "Não informado",
  "ABERTA DOS MORR": "Aberta dos Morros",
  AGRONOMIA: "Agronomia",
  ANCHIETA: "Anchieta",
  ARQUIPELAGO: "Arquipélago",
  AUXILIADORA: "Auxiliadora",
  AZENHA: "Azenha",
  "BELA VISTA": "Bela Vista",
  "BELEM NOVO": "Belém Novo",
  "BELEM VELHO": "Belém Velho",
  "BOA VISTA": "Boa Vista",
  "BOA VISTA DO SU": "Boa Vista do Sul",
  "BOM FIM": "Bom Fim",
  "BOM JESUS": "Bom Jesus",
  CAMAQUA: "Camaquã",
  "CAMPO NOVO": "Campo Novo",
  CASCATA: "Cascata",
  CAVALHADA: "Cavalhada",
  "CEL AP BORGES": "Cel. Aparício Borges",
  "CENTRO HISTORIC": "Centro Histórico",
  "CHACARA PEDRAS": "Chácara das Pedras",
  "CHAPEU DO SOL": "Chapéu do Sol",
  "CIDADE BAIXA": "Cidade Baixa",
  "COSTA E SILVA": "Costa e Silva",
  CRISTAL: "Cristal",
  "CRISTO REDENTOR": "Cristo Redentor",
  "ESPIRITO SANTO": "Espírito Santo",
  EXTREMA: "Extrema",
  FARRAPOS: "Farrapos",
  FARROUPILHA: "Farroupilha",
  FLORESTA: "Floresta",
  GLORIA: "Glória",
  GUARUJA: "Guarujá",
  HIGIENOPOLIS: "Higienópolis",
  HIPICA: "Hípica",
  HUMAITA: "Humaitá",
  INDEPENDENCIA: "Independência",
  IPANEMA: "Ipanema",
  "JAR ITU SABARA": "Jardim Itu Sabará",
  "JAR LEOPOLDINA": "Jardim Leopoldina",
  "JAR SAO PEDRO": "Jardim São Pedro",
  "JARDIM BOTANICO": "Jardim Botânico",
  "JARDIM CARVALHO": "Jardim Carvalho",
  "JARDIM DO SALSO": "Jardim do Salso",
  "JARDIM EUROPA": "Jardim Europa",
  "JARDIM FLORESTA": "Jardim Floresta",
  "JARDIM ISABEL": "Jardim Isabel",
  "JARDIM ITU": "Jardim Itu",
  "JARDIM LINDOIA": "Jardim Lindóia",
  "JARDIM SABARA": "Jardim Sabará",
  LAGEADO: "Lageado",
  LAMI: "Lami",
  "LOMBA PINHEIRO": "Lomba do Pinheiro",
  "MARIO QUINTANA": "Mário Quintana",
  MEDIANEIRA: "Medianeira",
  "MENINO DEUS": "Menino Deus",
  "MOINHOS VENTO": "Moinhos de Vento",
  "MONT SERRAT": "Mont Serrat",
  "MORRO SANTANA": "Morro Santana",
  NAVEGANTES: "Navegantes",
  NONOAI: "Nonoai",
  "PARQUE STA FE": "Parque Santa Fé",
  PARTENON: "Partenon",
  "PASSO DA AREIA": "Passo da Areia",
  "PASSO DAS PEDRA": "Passo das Pedras",
  "PASSO PEDRAS": "Passo das Pedras",
  "PEDRA REDONDA": "Pedra Redonda",
  PETROPOLIS: "Petrópolis",
  PITINGA: "Pitinga",
  "PONTA GROSSA": "Ponta Grossa",
  "PRAIA DE BELAS": "Praia de Belas",
  RESTINGA: "Restinga",
  "RIO BRANCO": "Rio Branco",
  "RUBEM BERTA": "Rubem Berta",
  "SANTA CECILIA": "Santa Cecília",
  "SANTA M GORETTI": "Santa Maria Goretti",
  "SANTA TEREZA": "Santa Tereza",
  SANTANA: "Santana",
  "SANTO ANTONIO": "Santo Antônio",
  "SAO CAETANO": "São Caetano",
  "SAO GERALDO": "São Geraldo",
  "SAO JOAO": "São João",
  "SAO SEBASTIAO": "São Sebastião",
  SARANDI: "Sarandi",
  SERRARIA: "Serraria",
  "SETIMO CEU": "Sétimo Céu",
  "STA ROSA LIMA": "Santa Rosa de Lima",
  TERESOPOLIS: "Teresópolis",
  "TRES FIGUEIRAS": "Três Figueiras",
  TRISTEZA: "Tristeza",
  "VILA ASSUNCAO": "Vila Assunção",
  "VILA CONCEICAO": "Vila Conceição",
  "VILA IPIRANGA": "Vila Ipiranga",
  "VILA JARDIM": "Vila Jardim",
  "VILA NOVA": "Vila Nova",
  "VILA SAO JOSE": "Vila São José",
  "VL JOAO PESSOA": "Vila João Pessoa",
  "VL SAO JOSE": "Vila São José",
  "ZN INDEFINIDA 2": "Zona Indefinida",
};

export function bairroDisplay(raw: string): string {
  return BAIRRO_DISPLAY[raw] ?? raw;
}